# Generated by Django 3.2.4 on 2021-06-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(default='maheshwarvaranasi@gmail.com', max_length=225, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SleepTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('sleepTime', models.TextField()),
                ('wakeupTime', models.TextField()),
                ('duration', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sleeptime.user')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
